# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: afaa247278aad0ce7f4ede1b91680209ef7a1d4f7bbc2b3d58b8e136a84dbcd90b69c3ac2205eabd5a0884e9f9a5d138a36f8f9c2687a88ff8f5e79bddee23d4

test:
  secret_key_base: 49716002068f4c695d22c5ed9415309fcfbd99fee3999ae2d3ac2db6bc8fd1122606617229918f7577d9e9ada23aaa883d965e619030ad5d002e2a3ee2ab7cff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
  FB_APP_SECRET: 'b0474049ada02b681a161a9097c3d99f'
  